import { sqliteTable, text, integer, primaryKey, type AnySQLiteColumn } from 'drizzle-orm/sqlite-core';
import { relations, sql } from 'drizzle-orm';
import { randomUUID } from 'crypto';
import type { BatchProvider, CredentialAuthType, CredentialConfig, CredentialType, FlowlibDefinitionRuntime, JSONValue, TriggerType } from '@flowlib/core/types';
import type { BatchStatus, FlowRunStatus, NodeExecutionStatus } from '@flowlib/action-kit';

// =============================================================================
// Flowlib tables — AUTO-GENERATED by @flowlib/cli
// Do not edit below this line. Run `npx flowlib-cli generate` to regenerate.
// =============================================================================

type FlowAccessPermission = string;
type NodeErrorDetails = string;

export const user = sqliteTable('flowlib_user', {
  id: text('id').primaryKey().notNull(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: integer('email_verified', { mode: 'boolean' }).notNull().default(false),
  image: text('image'),
  role: text('role').default('default'),
  banned: integer('banned', { mode: 'boolean' }).default(false),
  banReason: text('ban_reason'),
  banExpires: text('ban_expires'),
  twoFactorEnabled: integer('two_factor_enabled', { mode: 'boolean' }).default(false),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const account = sqliteTable('flowlib_account', {
  id: text('id').primaryKey().notNull(),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  idToken: text('id_token'),
  accessTokenExpiresAt: text('access_token_expires_at'),
  refreshTokenExpiresAt: text('refresh_token_expires_at'),
  scope: text('scope'),
  password: text('password'),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const session = sqliteTable('flowlib_session', {
  id: text('id').primaryKey().notNull(),
  expiresAt: text('expires_at').notNull(),
  token: text('token').notNull().unique(),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  impersonatedBy: text('impersonated_by'),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
});

export const verification = sqliteTable('flowlib_verification', {
  id: text('id').primaryKey().notNull(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: text('expires_at').notNull(),
  createdAt: text('created_at'),
  updatedAt: text('updated_at'),
});

export const apikey = sqliteTable('flowlib_apikey', {
  id: text('id').primaryKey().notNull(),
  configId: text('config_id').notNull().default('default'),
  name: text('name'),
  start: text('start'),
  prefix: text('prefix'),
  key: text('key').notNull(),
  referenceId: text('reference_id').notNull(),
  refillInterval: integer('refill_interval'),
  refillAmount: integer('refill_amount'),
  lastRefillAt: text('last_refill_at'),
  enabled: integer('enabled', { mode: 'boolean' }).default(true),
  rateLimitEnabled: integer('rate_limit_enabled', { mode: 'boolean' }),
  rateLimitTimeWindow: integer('rate_limit_time_window'),
  rateLimitMax: integer('rate_limit_max'),
  requestCount: integer('request_count'),
  remaining: integer('remaining'),
  lastRequest: text('last_request'),
  expiresAt: text('expires_at'),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  permissions: text('permissions'),
  metadata: text('metadata'),
});

export const flowAccess = sqliteTable('flowlib_flow_access', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  flowId: text('flow_id').notNull().references(() => flows.id, { onDelete: 'cascade' }),
  userId: text('user_id'),
  teamId: text('team_id'),
  permission: text('permission').notNull().default('viewer'),
  grantedBy: text('granted_by'),
  grantedAt: text('granted_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  expiresAt: text('expires_at'),
});

export const twoFactor = sqliteTable('flowlib_two_factor', {
  id: text('id').primaryKey().notNull(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  secret: text('secret').notNull(),
  backupCodes: text('backup_codes').notNull(),
  verified: integer('verified', { mode: 'boolean' }).default(false),
});

export const settings = sqliteTable('flowlib_settings', {
  key: text('key').primaryKey().notNull(),
  namespace: text('namespace').notNull(),
  value: text('value', { mode: 'json' }).$type<unknown>(),
  encrypted: integer('encrypted', { mode: 'boolean' }).notNull().default(false),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedBy: text('updated_by'),
});

export const credentials = sqliteTable('flowlib_credentials', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  name: text('name').notNull(),
  type: text('type').$type<CredentialType>().notNull(),
  authType: text('auth_type').$type<CredentialAuthType>().notNull(),
  config: text('config', { mode: 'json' }).$type<CredentialConfig>().notNull(),
  description: text('description'),
  isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
  workspaceId: text('workspace_id'),
  isShared: integer('is_shared', { mode: 'boolean' }).notNull().default(false),
  metadata: text('metadata', { mode: 'json' }).$type<Record<string, unknown>>(),
  lastUsedAt: text('last_used_at'),
  expiresAt: text('expires_at'),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const flows = sqliteTable('flowlib_flows', {
  id: text('id').primaryKey().notNull(),
  name: text('name').notNull(),
  description: text('description'),
  tags: text('tags', { mode: 'json' }).$type<string[]>(),
  isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
  liveVersionNumber: integer('live_version_number'),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  scope_id: text('scope_id').references(() => rbac_teams.id, { onDelete: 'set null' }),
});

export const vc_sync_config = sqliteTable('flowlib_vc_sync_config', {
  id: text('id').primaryKey().notNull(),
  flowId: text('flow_id').notNull().unique().references(() => flows.id, { onDelete: 'cascade' }),
  provider: text('provider').notNull(),
  repo: text('repo').notNull(),
  branch: text('branch').notNull(),
  filePath: text('file_path').notNull(),
  mode: text('mode').notNull(),
  syncDirection: text('sync_direction').notNull().default('write'),
  lastSyncedAt: text('last_synced_at'),
  lastCommitSha: text('last_commit_sha'),
  lastSyncedVersion: integer('last_synced_version'),
  draftBranch: text('draft_branch'),
  activePrNumber: integer('active_pr_number'),
  activePrUrl: text('active_pr_url'),
  enabled: integer('enabled', { mode: 'boolean' }).notNull().default(true),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const agent_role_permissions = sqliteTable('agent_role_permissions', {
  roleId: text('role_id').notNull(),
  toolName: text('tool_name').notNull(),
  enabled: integer('enabled', { mode: 'boolean' }).notNull().default(true),
  reason: text('reason'),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [primaryKey({ columns: [table.roleId, table.toolName] })]);

export const flowTriggers = sqliteTable('flowlib_flow_triggers', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  flowId: text('flow_id').notNull().references(() => flows.id, { onDelete: 'cascade' }),
  nodeId: text('node_id').notNull(),
  type: text('type').$type<TriggerType>().notNull(),
  isEnabled: integer('is_enabled', { mode: 'boolean' }).notNull().default(true),
  webhookPath: text('webhook_path').unique(),
  webhookSecret: text('webhook_secret'),
  cronExpression: text('cron_expression'),
  cronTimezone: text('cron_timezone'),
  lastTriggeredAt: text('last_triggered_at'),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const flowVersions = sqliteTable('flowlib_flow_versions', {
  flowId: text('flow_id').notNull().references(() => flows.id, { onDelete: 'cascade' }),
  version: integer('version').notNull(),
  flowlibDefinition: text('flowlib_definition', { mode: 'json' }).$type<FlowlibDefinitionRuntime>().notNull(),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  createdBy: text('created_by'),
}, (table) => [primaryKey({ columns: [table.version, table.flowId] })]);

export const vc_sync_history = sqliteTable('flowlib_vc_sync_history', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  flowId: text('flow_id').notNull().references(() => flows.id, { onDelete: 'cascade' }),
  action: text('action').notNull(),
  commitSha: text('commit_sha'),
  prNumber: integer('pr_number'),
  version: integer('version'),
  message: text('message'),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  createdBy: text('created_by'),
});

export const agent_projects = sqliteTable('agent_projects', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  orgId: text('org_id'),
  name: text('name').notNull(),
  description: text('description'),
  gitRemote: text('git_remote'),
  createdBy: text('created_by').notNull(),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const chatMessages = sqliteTable('flowlib_chat_messages', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  flowId: text('flow_id').notNull().references(() => flows.id, { onDelete: 'cascade' }),
  role: text('role').$type<'user' | 'assistant' | 'system' | 'tool'>().notNull(),
  content: text('content').notNull().default(''),
  toolMeta: text('tool_meta', { mode: 'json' }).$type<Record<string, unknown>>(),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const flowRuns = sqliteTable('flowlib_flow_executions', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  flowId: text('flow_id').notNull().references(() => flows.id, { onDelete: 'cascade' }),
  flowVersion: integer('flow_version').notNull(),
  status: text('status').$type<FlowRunStatus>().notNull().default(sql`'PENDING'`),
  inputs: text('inputs', { mode: 'json' }).$type<JSONValue>().notNull(),
  outputs: text('outputs', { mode: 'json' }).$type<JSONValue>(),
  error: text('error'),
  startedAt: text('started_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  completedAt: text('completed_at'),
  duration: integer('duration'),
  createdBy: text('created_by'),
  triggerType: text('trigger_type'),
  triggerId: text('trigger_id'),
  triggerNodeId: text('trigger_node_id'),
  triggerData: text('trigger_data', { mode: 'json' }).$type<JSONValue>(),
  lastHeartbeatAt: text('last_heartbeat_at'),
  nodeOutputs: text('node_outputs', { mode: 'json' }).$type<JSONValue>(),
});

export const vc_instance_state = sqliteTable('flowlib_vc_instance_state', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  repo: text('repo').notNull(),
  branch: text('branch').notNull(),
  lastInstanceCommitSha: text('last_instance_commit_sha'),
  lastReconcilerTickAt: text('last_reconciler_tick_at'),
  lastReconcilerError: text('last_reconciler_error'),
  breakGlassUntil: text('break_glass_until'),
  breakGlassActor: text('break_glass_actor'),
  breakGlassReason: text('break_glass_reason'),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const actionTraces = sqliteTable('flowlib_action_traces', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  flowRunId: text('flow_run_id').notNull().references(() => flowRuns.id, { onDelete: 'cascade' }),
  parentNodeExecutionId: text('parent_node_execution_id').references((): AnySQLiteColumn => actionTraces.id, { onDelete: 'cascade' }),
  nodeId: text('node_id'),
  nodeType: text('node_type'),
  toolId: text('tool_id'),
  toolName: text('tool_name'),
  iteration: integer('iteration'),
  status: text('status').$type<NodeExecutionStatus>().notNull().default(sql`'PENDING'`),
  inputs: text('inputs', { mode: 'json' }).$type<JSONValue>().notNull(),
  outputs: text('outputs', { mode: 'json' }).$type<JSONValue>(),
  error: text('error', { mode: 'json' }).$type<NodeErrorDetails>(),
  startedAt: text('started_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  completedAt: text('completed_at'),
  duration: integer('duration'),
  retryCount: integer('retry_count').notNull().default(0),
});

export const agent_workspaces = sqliteTable('agent_workspaces', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  orgId: text('org_id'),
  name: text('name').notNull(),
  workspaceProviderId: text('workspace_provider_id').notNull(),
  rootPath: text('root_path'),
  gitRemote: text('git_remote'),
  gitBranch: text('git_branch'),
  sandboxConfig: text('sandbox_config', { mode: 'json' }).$type<Record<string, unknown>>(),
  projectId: text('project_id'),
  createdBy: text('created_by').notNull(),
  visibility: text('visibility').notNull().default('private'),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const vc_pull_commits = sqliteTable('flowlib_vc_pull_commits', {
  flowId: text('flow_id').notNull().references(() => flows.id, { onDelete: 'cascade' }),
  commitSha: text('commit_sha').notNull(),
  versionInserted: integer('version_inserted'),
  pulledAt: text('pulled_at').notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [primaryKey({ columns: [table.flowId, table.commitSha] })]);

export const agent_mcp_servers = sqliteTable('agent_mcp_servers', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  orgId: text('org_id'),
  name: text('name').notNull(),
  description: text('description'),
  transport: text('transport').notNull(),
  config: text('config', { mode: 'json' }).$type<Record<string, unknown>>().notNull().default(sql`'{}'`),
  createdBy: text('created_by').notNull(),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const batchJobs = sqliteTable('flowlib_batch_jobs', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  flowRunId: text('flow_run_id').notNull().references(() => flowRuns.id, { onDelete: 'cascade' }),
  nodeId: text('node_id').notNull(),
  provider: text('provider').$type<BatchProvider>().notNull(),
  batchId: text('batch_id'),
  status: text('status').$type<BatchStatus>().notNull().default(sql`'SUBMITTED'`),
  requestData: text('request_data', { mode: 'json' }).notNull(),
  responseData: text('response_data', { mode: 'json' }),
  error: text('error'),
  submittedAt: text('submitted_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  completedAt: text('completed_at'),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const vc_status_cache = sqliteTable('flowlib_vc_status_cache', {
  flowId: text('flow_id').primaryKey().notNull().references(() => flows.id, { onDelete: 'cascade' }),
  state: text('state').notNull(),
  chipLabel: text('chip_label').notNull(),
  actionLabel: text('action_label'),
  lastError: text('last_error'),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const agent_workspace_shares = sqliteTable('agent_workspace_shares', {
  orgId: text('org_id'),
  workspaceId: text('workspace_id').notNull().references(() => agent_workspaces.id, { onDelete: 'cascade' }),
  userId: text('user_id').notNull(),
  role: text('role').notNull(),
  grantedBy: text('granted_by').notNull(),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [primaryKey({ columns: [table.workspaceId, table.userId] })]);

export const agent_sessions = sqliteTable('agent_sessions', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  orgId: text('org_id'),
  providerSessionId: text('provider_session_id').notNull(),
  title: text('title').notNull().default('New chat'),
  providerId: text('provider_id').notNull(),
  providerConfig: text('provider_config', { mode: 'json' }).$type<Record<string, unknown>>().notNull().default(sql`'{}'`),
  credentialId: text('credential_id'),
  model: text('model'),
  permissionMode: text('permission_mode'),
  systemPrompt: text('system_prompt'),
  workspaceId: text('workspace_id').references(() => agent_workspaces.id, { onDelete: 'no action' }),
  enabledMcpServerIds: text('enabled_mcp_server_ids', { mode: 'json' }).$type<string[]>().notNull().default(sql`'[]'`),
  enabledTools: text('enabled_tools', { mode: 'json' }).$type<string[]>(),
  denyList: text('deny_list', { mode: 'json' }).$type<string[]>(),
  exposeFlowlibActions: integer('expose_flowlib_actions', { mode: 'boolean' }).notNull().default(false),
  toolOutputBudget: text('tool_output_budget', { mode: 'json' }).$type<{ lines: number; bytes: number }>().notNull().default(sql`'{"lines":100,"bytes":4096}'`),
  createdBy: text('created_by').notNull(),
  visibility: text('visibility').notNull().default('private'),
  status: text('status').notNull().default('active'),
  lastMessageAt: text('last_message_at'),
  messageCount: integer('message_count').notNull().default(0),
  inputTokensTotal: integer('input_tokens_total').notNull().default(0),
  outputTokensTotal: integer('output_tokens_total').notNull().default(0),
  costUsd: text('cost_usd').notNull().default('0'),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const agent_session_shares = sqliteTable('agent_session_shares', {
  orgId: text('org_id'),
  sessionId: text('session_id').notNull().references(() => agent_sessions.id, { onDelete: 'cascade' }),
  userId: text('user_id').notNull(),
  role: text('role').notNull(),
  grantedBy: text('granted_by').notNull(),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [primaryKey({ columns: [table.sessionId, table.userId] })]);

export const agent_messages = sqliteTable('agent_messages', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  orgId: text('org_id'),
  sessionId: text('session_id').notNull().references(() => agent_sessions.id, { onDelete: 'cascade' }),
  sequence: integer('sequence').notNull(),
  parentMessageId: text('parent_message_id'),
  role: text('role').notNull(),
  parts: text('parts', { mode: 'json' }).$type<unknown[]>().notNull().default(sql`'[]'`),
  usage: text('usage', { mode: 'json' }).$type<Record<string, number>>(),
  costUsd: text('cost_usd').notNull().default('0'),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  userId: text('user_id'),
});

export const agent_attachments = sqliteTable('agent_attachments', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  orgId: text('org_id'),
  sessionId: text('session_id').notNull().references(() => agent_sessions.id, { onDelete: 'cascade' }),
  messageId: text('message_id').notNull().references(() => agent_messages.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  mediaType: text('media_type').notNull(),
  sizeBytes: integer('size_bytes').notNull(),
  storageKey: text('storage_key').notNull(),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const rbac_scope_access = sqliteTable('flowlib_rbac_scope_access', {
  id: text('id').primaryKey().notNull(),
  scope_id: text('scope_id').notNull().references(() => rbac_teams.id, { onDelete: 'cascade' }),
  user_id: text('user_id'),
  team_id: text('team_id'),
  permission: text('permission').$type<FlowAccessPermission>().notNull().default(sql`'viewer'`),
  granted_by: text('granted_by'),
  granted_at: text('granted_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const rbac_team_members = sqliteTable('flowlib_rbac_team_members', {
  id: text('id').primaryKey().notNull(),
  team_id: text('team_id').notNull().references(() => rbac_teams.id, { onDelete: 'cascade' }),
  user_id: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  created_at: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const rbac_teams = sqliteTable('flowlib_rbac_teams', {
  id: text('id').primaryKey().notNull(),
  name: text('name').notNull(),
  description: text('description'),
  parent_id: text('parent_id').references((): AnySQLiteColumn => rbac_teams.id, { onDelete: 'set null' }),
  created_by: text('created_by').references(() => user.id, { onDelete: 'no action' }),
  created_at: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updated_at: text('updated_at'),
});

export const webhook_triggers = sqliteTable('flowlib_webhook_triggers', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  name: text('name').notNull(),
  description: text('description'),
  webhookPath: text('webhook_path').notNull().unique(),
  provider: text('provider').notNull().default('generic'),
  isEnabled: integer('is_enabled', { mode: 'boolean' }).notNull().default(true),
  allowedMethods: text('allowed_methods').notNull().default('POST'),
  hmacEnabled: integer('hmac_enabled', { mode: 'boolean' }).notNull().default(false),
  hmacHeaderName: text('hmac_header_name'),
  hmacSecret: text('hmac_secret'),
  allowedIps: text('allowed_ips'),
  flowId: text('flow_id').references(() => flows.id, { onDelete: 'no action' }),
  nodeId: text('node_id'),
  remoteWebhookId: text('remote_webhook_id'),
  remoteCredentialId: text('remote_credential_id').references(() => credentials.id, { onDelete: 'set null' }),
  remoteProvider: text('remote_provider'),
  remoteScope: text('remote_scope', { mode: 'json' }),
  remoteEvents: text('remote_events', { mode: 'json' }),
  lastTriggeredAt: text('last_triggered_at'),
  lastPayload: text('last_payload', { mode: 'json' }),
  triggerCount: integer('trigger_count').notNull().default(0),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const agent_file_edits = sqliteTable('agent_file_edits', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  orgId: text('org_id'),
  sessionId: text('session_id').notNull().references(() => agent_sessions.id, { onDelete: 'cascade' }),
  messageId: text('message_id').notNull().references(() => agent_messages.id, { onDelete: 'cascade' }),
  path: text('path').notNull(),
  beforeSha: text('before_sha'),
  afterSha: text('after_sha'),
  kind: text('kind').notNull(),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const agent_session_plans = sqliteTable('agent_session_plans', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  orgId: text('org_id'),
  sessionId: text('session_id').notNull().unique().references(() => agent_sessions.id, { onDelete: 'cascade' }),
  checkpoints: text('checkpoints', { mode: 'json' }).$type<Array<{ id: string; label: string; status: string }>>().notNull().default(sql`'[]'`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const agent_skills = sqliteTable('agent_skills', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  orgId: text('org_id'),
  name: text('name').notNull(),
  description: text('description').notNull(),
  body: text('body').notNull(),
  scope: text('scope').notNull().default('personal'),
  ownerId: text('owner_id'),
  tags: text('tags', { mode: 'json' }).$type<string[]>(),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const agent_memories = sqliteTable('agent_memories', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  orgId: text('org_id'),
  scope: text('scope').notNull(),
  userId: text('user_id'),
  projectId: text('project_id'),
  content: text('content').notNull(),
  embedding: text('embedding'),
  tags: text('tags', { mode: 'json' }).$type<string[]>(),
  createdBy: text('created_by').notNull(),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  lastUsedAt: text('last_used_at'),
});

export const agent_pending_human_actions = sqliteTable('agent_pending_human_actions', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  orgId: text('org_id'),
  sessionId: text('session_id').notNull().references(() => agent_sessions.id, { onDelete: 'cascade' }),
  description: text('description').notNull(),
  link: text('link'),
  pollerConfig: text('poller_config', { mode: 'json' }).$type<Record<string, unknown>>(),
  state: text('state').notNull().default('pending'),
  resolution: text('resolution', { mode: 'json' }).$type<Record<string, unknown>>(),
  timeoutAt: text('timeout_at'),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  resolvedAt: text('resolved_at'),
});

export const agent_audit_events = sqliteTable('agent_audit_events', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  orgId: text('org_id'),
  sessionId: text('session_id').notNull(),
  userId: text('user_id').notNull(),
  eventType: text('event_type').notNull(),
  toolName: text('tool_name'),
  payload: text('payload', { mode: 'json' }).$type<Record<string, unknown>>().notNull().default(sql`'{}'`),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const userRelations = relations(user, ({ many }) => ({
  account: many(account),
  session: many(session),
  twoFactor: many(twoFactor),
  rbac_team_members: many(rbac_team_members),
  rbac_teams: many(rbac_teams),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, { fields: [account.userId], references: [user.id] }),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, { fields: [session.userId], references: [user.id] }),
}));

export const flowAccessRelations = relations(flowAccess, ({ one }) => ({
  flow: one(flows, { fields: [flowAccess.flowId], references: [flows.id] }),
}));

export const twoFactorRelations = relations(twoFactor, ({ one }) => ({
  user: one(user, { fields: [twoFactor.userId], references: [user.id] }),
}));

export const credentialsRelations = relations(credentials, ({ many }) => ({
  webhook_triggers: many(webhook_triggers),
}));

export const flowsRelations = relations(flows, ({ one, many }) => ({
  scope: one(rbac_teams, { fields: [flows.scope_id], references: [rbac_teams.id] }),
  flowAccess: many(flowAccess),
  vc_sync_config: many(vc_sync_config),
  flowTriggers: many(flowTriggers),
  flowVersions: many(flowVersions),
  vc_sync_history: many(vc_sync_history),
  chatMessages: many(chatMessages),
  flowRuns: many(flowRuns),
  vc_pull_commits: many(vc_pull_commits),
  vc_status_cache: many(vc_status_cache),
  webhook_triggers: many(webhook_triggers),
}));

export const vc_sync_configRelations = relations(vc_sync_config, ({ one }) => ({
  flow: one(flows, { fields: [vc_sync_config.flowId], references: [flows.id] }),
}));

export const flowTriggersRelations = relations(flowTriggers, ({ one }) => ({
  flow: one(flows, { fields: [flowTriggers.flowId], references: [flows.id] }),
}));

export const flowVersionsRelations = relations(flowVersions, ({ one }) => ({
  flow: one(flows, { fields: [flowVersions.flowId], references: [flows.id] }),
}));

export const vc_sync_historyRelations = relations(vc_sync_history, ({ one }) => ({
  flow: one(flows, { fields: [vc_sync_history.flowId], references: [flows.id] }),
}));

export const chatMessagesRelations = relations(chatMessages, ({ one }) => ({
  flow: one(flows, { fields: [chatMessages.flowId], references: [flows.id] }),
}));

export const flowRunsRelations = relations(flowRuns, ({ one, many }) => ({
  flow: one(flows, { fields: [flowRuns.flowId], references: [flows.id] }),
  actionTraces: many(actionTraces),
  batchJobs: many(batchJobs),
}));

export const actionTracesRelations = relations(actionTraces, ({ one, many }) => ({
  flowRun: one(flowRuns, { fields: [actionTraces.flowRunId], references: [flowRuns.id] }),
  parentNodeExecution: one(actionTraces, { fields: [actionTraces.parentNodeExecutionId], references: [actionTraces.id] }),
  actionTraces: many(actionTraces),
}));

export const agent_workspacesRelations = relations(agent_workspaces, ({ many }) => ({
  agent_workspace_shares: many(agent_workspace_shares),
  agent_sessions: many(agent_sessions),
}));

export const vc_pull_commitsRelations = relations(vc_pull_commits, ({ one }) => ({
  flow: one(flows, { fields: [vc_pull_commits.flowId], references: [flows.id] }),
}));

export const batchJobsRelations = relations(batchJobs, ({ one }) => ({
  flowRun: one(flowRuns, { fields: [batchJobs.flowRunId], references: [flowRuns.id] }),
}));

export const vc_status_cacheRelations = relations(vc_status_cache, ({ one }) => ({
  flow: one(flows, { fields: [vc_status_cache.flowId], references: [flows.id] }),
}));

export const agent_workspace_sharesRelations = relations(agent_workspace_shares, ({ one }) => ({
  workspace: one(agent_workspaces, { fields: [agent_workspace_shares.workspaceId], references: [agent_workspaces.id] }),
}));

export const agent_sessionsRelations = relations(agent_sessions, ({ one, many }) => ({
  workspace: one(agent_workspaces, { fields: [agent_sessions.workspaceId], references: [agent_workspaces.id] }),
  agent_session_shares: many(agent_session_shares),
  agent_messages: many(agent_messages),
  agent_attachments: many(agent_attachments),
  agent_file_edits: many(agent_file_edits),
  agent_session_plans: many(agent_session_plans),
  agent_pending_human_actions: many(agent_pending_human_actions),
}));

export const agent_session_sharesRelations = relations(agent_session_shares, ({ one }) => ({
  session: one(agent_sessions, { fields: [agent_session_shares.sessionId], references: [agent_sessions.id] }),
}));

export const agent_messagesRelations = relations(agent_messages, ({ one, many }) => ({
  session: one(agent_sessions, { fields: [agent_messages.sessionId], references: [agent_sessions.id] }),
  agent_attachments: many(agent_attachments),
  agent_file_edits: many(agent_file_edits),
}));

export const agent_attachmentsRelations = relations(agent_attachments, ({ one }) => ({
  session: one(agent_sessions, { fields: [agent_attachments.sessionId], references: [agent_sessions.id] }),
  message: one(agent_messages, { fields: [agent_attachments.messageId], references: [agent_messages.id] }),
}));

export const rbac_scope_accessRelations = relations(rbac_scope_access, ({ one }) => ({
  scope: one(rbac_teams, { fields: [rbac_scope_access.scope_id], references: [rbac_teams.id] }),
}));

export const rbac_team_membersRelations = relations(rbac_team_members, ({ one }) => ({
  team: one(rbac_teams, { fields: [rbac_team_members.team_id], references: [rbac_teams.id] }),
  user: one(user, { fields: [rbac_team_members.user_id], references: [user.id] }),
}));

export const rbac_teamsRelations = relations(rbac_teams, ({ one, many }) => ({
  parent: one(rbac_teams, { fields: [rbac_teams.parent_id], references: [rbac_teams.id] }),
  created_by: one(user, { fields: [rbac_teams.created_by], references: [user.id] }),
  flows: many(flows),
  rbac_scope_access: many(rbac_scope_access),
  rbac_team_members: many(rbac_team_members),
  rbac_teams: many(rbac_teams),
}));

export const webhook_triggersRelations = relations(webhook_triggers, ({ one }) => ({
  flow: one(flows, { fields: [webhook_triggers.flowId], references: [flows.id] }),
  remoteCredential: one(credentials, { fields: [webhook_triggers.remoteCredentialId], references: [credentials.id] }),
}));

export const agent_file_editsRelations = relations(agent_file_edits, ({ one }) => ({
  session: one(agent_sessions, { fields: [agent_file_edits.sessionId], references: [agent_sessions.id] }),
  message: one(agent_messages, { fields: [agent_file_edits.messageId], references: [agent_messages.id] }),
}));

export const agent_session_plansRelations = relations(agent_session_plans, ({ one }) => ({
  session: one(agent_sessions, { fields: [agent_session_plans.sessionId], references: [agent_sessions.id] }),
}));

export const agent_pending_human_actionsRelations = relations(agent_pending_human_actions, ({ one }) => ({
  session: one(agent_sessions, { fields: [agent_pending_human_actions.sessionId], references: [agent_sessions.id] }),
}));


export type User = typeof user.$inferSelect;
export type NewUser = typeof user.$inferInsert;
export type Account = typeof account.$inferSelect;
export type NewAccount = typeof account.$inferInsert;
export type Session = typeof session.$inferSelect;
export type NewSession = typeof session.$inferInsert;
export type Verification = typeof verification.$inferSelect;
export type NewVerification = typeof verification.$inferInsert;
export type Apikey = typeof apikey.$inferSelect;
export type NewApikey = typeof apikey.$inferInsert;
export type FlowAccess = typeof flowAccess.$inferSelect;
export type NewFlowAccess = typeof flowAccess.$inferInsert;
export type TwoFactor = typeof twoFactor.$inferSelect;
export type NewTwoFactor = typeof twoFactor.$inferInsert;
export type Settings = typeof settings.$inferSelect;
export type NewSettings = typeof settings.$inferInsert;
export type Credentials = typeof credentials.$inferSelect;
export type NewCredentials = typeof credentials.$inferInsert;
export type Flows = typeof flows.$inferSelect;
export type NewFlows = typeof flows.$inferInsert;
export type Vc_sync_config = typeof vc_sync_config.$inferSelect;
export type NewVc_sync_config = typeof vc_sync_config.$inferInsert;
export type Agent_role_permissions = typeof agent_role_permissions.$inferSelect;
export type NewAgent_role_permissions = typeof agent_role_permissions.$inferInsert;
export type FlowTriggers = typeof flowTriggers.$inferSelect;
export type NewFlowTriggers = typeof flowTriggers.$inferInsert;
export type FlowVersions = typeof flowVersions.$inferSelect;
export type NewFlowVersions = typeof flowVersions.$inferInsert;
export type Vc_sync_history = typeof vc_sync_history.$inferSelect;
export type NewVc_sync_history = typeof vc_sync_history.$inferInsert;
export type Agent_projects = typeof agent_projects.$inferSelect;
export type NewAgent_projects = typeof agent_projects.$inferInsert;
export type ChatMessages = typeof chatMessages.$inferSelect;
export type NewChatMessages = typeof chatMessages.$inferInsert;
export type FlowRuns = typeof flowRuns.$inferSelect;
export type NewFlowRuns = typeof flowRuns.$inferInsert;
export type Vc_instance_state = typeof vc_instance_state.$inferSelect;
export type NewVc_instance_state = typeof vc_instance_state.$inferInsert;
export type ActionTraces = typeof actionTraces.$inferSelect;
export type NewActionTraces = typeof actionTraces.$inferInsert;
export type Agent_workspaces = typeof agent_workspaces.$inferSelect;
export type NewAgent_workspaces = typeof agent_workspaces.$inferInsert;
export type Vc_pull_commits = typeof vc_pull_commits.$inferSelect;
export type NewVc_pull_commits = typeof vc_pull_commits.$inferInsert;
export type Agent_mcp_servers = typeof agent_mcp_servers.$inferSelect;
export type NewAgent_mcp_servers = typeof agent_mcp_servers.$inferInsert;
export type BatchJobs = typeof batchJobs.$inferSelect;
export type NewBatchJobs = typeof batchJobs.$inferInsert;
export type Vc_status_cache = typeof vc_status_cache.$inferSelect;
export type NewVc_status_cache = typeof vc_status_cache.$inferInsert;
export type Agent_workspace_shares = typeof agent_workspace_shares.$inferSelect;
export type NewAgent_workspace_shares = typeof agent_workspace_shares.$inferInsert;
export type Agent_sessions = typeof agent_sessions.$inferSelect;
export type NewAgent_sessions = typeof agent_sessions.$inferInsert;
export type Agent_session_shares = typeof agent_session_shares.$inferSelect;
export type NewAgent_session_shares = typeof agent_session_shares.$inferInsert;
export type Agent_messages = typeof agent_messages.$inferSelect;
export type NewAgent_messages = typeof agent_messages.$inferInsert;
export type Agent_attachments = typeof agent_attachments.$inferSelect;
export type NewAgent_attachments = typeof agent_attachments.$inferInsert;
export type Rbac_scope_access = typeof rbac_scope_access.$inferSelect;
export type NewRbac_scope_access = typeof rbac_scope_access.$inferInsert;
export type Rbac_team_members = typeof rbac_team_members.$inferSelect;
export type NewRbac_team_members = typeof rbac_team_members.$inferInsert;
export type Rbac_teams = typeof rbac_teams.$inferSelect;
export type NewRbac_teams = typeof rbac_teams.$inferInsert;
export type Webhook_triggers = typeof webhook_triggers.$inferSelect;
export type NewWebhook_triggers = typeof webhook_triggers.$inferInsert;
export type Agent_file_edits = typeof agent_file_edits.$inferSelect;
export type NewAgent_file_edits = typeof agent_file_edits.$inferInsert;
export type Agent_session_plans = typeof agent_session_plans.$inferSelect;
export type NewAgent_session_plans = typeof agent_session_plans.$inferInsert;
export type Agent_skills = typeof agent_skills.$inferSelect;
export type NewAgent_skills = typeof agent_skills.$inferInsert;
export type Agent_memories = typeof agent_memories.$inferSelect;
export type NewAgent_memories = typeof agent_memories.$inferInsert;
export type Agent_pending_human_actions = typeof agent_pending_human_actions.$inferSelect;
export type NewAgent_pending_human_actions = typeof agent_pending_human_actions.$inferInsert;
export type Agent_audit_events = typeof agent_audit_events.$inferSelect;
export type NewAgent_audit_events = typeof agent_audit_events.$inferInsert;
