// =============================================================================
// Phase 4 — Manifest contract
//
// Each push emits / regenerates two artifacts:
//   1. A per-flow `@flowlib-requires` comment header on the `.flow.ts` source.
//      Informational; the JSON footer remains the authoritative round-trip.
//      Lets a reviewer see at the top of a diff what envs the flow needs.
//   2. An aggregate `flows/_manifest.json` listing every tracked flow's
//      required envs. Promotion uses this to render the PR body and to
//      gate (advisory v1, contract v2) the merge.
//
// Phase 4 v1 limitations (documented for later phases):
//   - Variables aren't tracked. The variables system itself doesn't have a
//     `secret` flag yet (PLAN.md §11.1 open question).
//   - "Contract" enforcement is advisory: the check endpoint reports missing
//     credentials but doesn't block the merge by itself. Blocking belongs to
//     a CI tool (`flowlib check` CLI — deferred to Phase 4 follow-up).
//   - Credential identity uses env-name only. Dev's `OPENAI_CREDENTIAL` and
//     prod's `OPENAI_CREDENTIAL` may have different IDs / providers; the
//     manifest tracks names + provider hints, the target instance does the
//     name-based lookup. Type drift detection (PLAN.md §E.4) is post-v1.
// =============================================================================

const FOOTER_START = '/* @flowlib-definition';
const REQUIRES_MARKER_START = '/* @flowlib-requires';
const REQUIRES_MARKER_END = '*/';

/** One flow's manifest entry. */
export interface FlowManifestEntry {
  /** Stable flowId — the contract identity (D1). */
  flowId: string;
  /** Human-readable flow name. Echoed for review UX. */
  name: string;
  /** Repo-relative path of the `.flow.ts` file. */
  filePath: string;
  /** Env names required by this flow's substituted credentials. */
  requires: {
    credentials: string[];
  };
}

/** The aggregate `flows/_manifest.json` shape. */
export interface AggregateManifest {
  /** Schema version — bump on incompatible field changes. */
  version: 1;
  /** ISO timestamp of when the manifest was generated. */
  generatedAt: string;
  /** Per-flow entries keyed by flowId for deterministic lookup. */
  flows: Record<string, FlowManifestEntry>;
}

/**
 * Extract every `{{env.NAME}}` placeholder from substituted `.flow.ts` source.
 *
 * Operates on the human-readable section only (everything before the JSON
 * footer) so it doesn't pick up references that round-trip through the
 * footer's raw credentialId fields. Returns sorted, deduped names.
 */
export function extractRequiredEnvs(content: string): string[] {
  const footerIdx = content.indexOf(FOOTER_START);
  const human = footerIdx === -1 ? content : content.slice(0, footerIdx);
  const matches = human.matchAll(/\{\{\s*env\.([A-Z][A-Z0-9_]*)\s*\}\}/g);
  const envs = new Set<string>();
  for (const m of matches) {
    envs.add(m[1]);
  }
  return Array.from(envs).sort();
}

/**
 * Prepend the `@flowlib-requires` comment header to substituted source.
 *
 * Idempotent — calling on already-decorated source replaces the existing
 * header rather than stacking comments. Empty `requires` produces a
 * comment that lists nothing (still useful: signals "no external deps").
 *
 * The header lives BEFORE the imports so a diff reader sees it first.
 * Format keeps trailing newlines exact so the emitter's output stays
 * stable for golden-file tests.
 */
export function decorateWithRequires(content: string, requires: string[]): string {
  const stripped = stripExistingRequires(content);
  if (requires.length === 0) {
    // Still write the header so reviewers know we checked. Empty list
    // means "no external credentials referenced" — meaningful signal.
    const header = `${REQUIRES_MARKER_START}\n *   credentials: (none)\n *\n * Auto-generated by @flowlib/version-control. Do not edit.\n ${REQUIRES_MARKER_END}\n`;
    return header + stripped;
  }
  const credLine = requires.join(', ');
  const header = `${REQUIRES_MARKER_START}\n *   credentials: ${credLine}\n *\n * Auto-generated by @flowlib/version-control. Do not edit.\n ${REQUIRES_MARKER_END}\n`;
  return header + stripped;
}

/** Remove an existing `@flowlib-requires` block, if any. */
function stripExistingRequires(content: string): string {
  if (!content.startsWith(REQUIRES_MARKER_START)) {
    return content;
  }
  const endIdx = content.indexOf(REQUIRES_MARKER_END, REQUIRES_MARKER_START.length);
  if (endIdx === -1) {
    return content;
  }
  // Skip the closing `*/` plus trailing newline if present.
  let after = endIdx + REQUIRES_MARKER_END.length;
  if (content[after] === '\n') {
    after++;
  }
  return content.slice(after);
}

/**
 * Build a single flow's manifest entry from its (already-substituted) source.
 *
 * The caller passes flow metadata; this function only extracts the
 * `requires` half. Pure — no IO.
 */
export function buildFlowManifestEntry(args: {
  content: string;
  flowId: string;
  name: string;
  filePath: string;
}): FlowManifestEntry {
  return {
    flowId: args.flowId,
    name: args.name,
    filePath: args.filePath,
    requires: {
      credentials: extractRequiredEnvs(args.content),
    },
  };
}

/**
 * Build the aggregate manifest from per-flow entries. The output is
 * deterministic (entries keyed by flowId, requires sorted) so two
 * independent generations of the same input produce byte-identical
 * JSON — keeps the PR diff clean.
 *
 * `generatedAt` is the only non-deterministic field; tests should pin it.
 */
export function buildAggregateManifest(
  entries: FlowManifestEntry[],
  options: { now?: () => Date } = {},
): AggregateManifest {
  const now = options.now ?? (() => new Date());
  const flows: Record<string, FlowManifestEntry> = {};
  // Sort entries by flowId so the JSON is canonical regardless of insert order.
  const sorted = [...entries].sort((a, b) => (a.flowId < b.flowId ? -1 : 1));
  for (const e of sorted) {
    flows[e.flowId] = {
      ...e,
      requires: { credentials: [...e.requires.credentials].sort() },
    };
  }
  return {
    version: 1,
    generatedAt: now().toISOString(),
    flows,
  };
}

/** Standard repo-relative path for the aggregate manifest. */
export function manifestFilePath(basePath: string): string {
  const trimmed = basePath.endsWith('/') ? basePath : `${basePath}/`;
  return `${trimmed}_manifest.json`;
}

/**
 * Serialize an aggregate manifest as pretty-printed JSON. Two-space indent
 * keeps PR diffs readable; trailing newline makes the file POSIX-friendly
 * (lots of tools complain about missing newline at EOF).
 */
export function serializeManifest(manifest: AggregateManifest): string {
  return JSON.stringify(manifest, null, 2) + '\n';
}

// =============================================================================
// Manifest validation against an instance
// =============================================================================

export interface ManifestCheckRequest {
  manifest: AggregateManifest;
}

export interface CredentialCheckResult {
  envName: string;
  /** Flow IDs that reference this env. */
  referencedBy: string[];
  /** True iff the target instance has a credential with this name. */
  satisfied: boolean;
}

export interface ManifestCheckResult {
  /** True iff every required credential is satisfied on the target. */
  ok: boolean;
  credentials: CredentialCheckResult[];
  /** Subset of `credentials` that aren't satisfied — convenience for UI. */
  missing: CredentialCheckResult[];
}

/**
 * Check whether the local instance's credentials satisfy the manifest's
 * required envs. Inverts the manifest into env → flowIds, then probes the
 * `flowlib_credentials` table by name (case-insensitive).
 *
 * Match logic for v1: case-insensitive name comparison after underscore /
 * space normalization, so `OPENAI_CREDENTIAL` matches `openai credential`
 * or `OpenAI_Credential` etc. Type drift checks (PLAN.md §E.4) are post-v1.
 */
export async function checkManifestAgainstInstance(
  db: import('@flowlib/core').PluginDatabaseApi,
  manifest: AggregateManifest,
): Promise<ManifestCheckResult> {
  // Invert: env → flow ids that reference it.
  const referencedBy = new Map<string, string[]>();
  for (const flow of Object.values(manifest.flows)) {
    for (const env of flow.requires.credentials) {
      const list = referencedBy.get(env) ?? [];
      list.push(flow.flowId);
      referencedBy.set(env, list);
    }
  }

  if (referencedBy.size === 0) {
    return { ok: true, credentials: [], missing: [] };
  }

  // Pull every credential name once, build a normalized set, then check
  // each required env. Cheaper than N queries when there are many envs.
  const rows = await db.query<{ name: string }>('SELECT name FROM flowlib_credentials');
  const available = new Set(rows.map((r) => normalizeName(r.name)));

  const credentials: CredentialCheckResult[] = [];
  for (const [env, flowIds] of referencedBy) {
    const satisfied = available.has(normalizeName(env));
    credentials.push({ envName: env, referencedBy: flowIds.sort(), satisfied });
  }
  credentials.sort((a, b) => (a.envName < b.envName ? -1 : 1));
  const missing = credentials.filter((c) => !c.satisfied);
  return {
    ok: missing.length === 0,
    credentials,
    missing,
  };
}

/**
 * Normalize a credential name for case-insensitive comparison. Strips
 * non-alphanumerics so "Open AI Credential", "openai_credential", and
 * "OPENAI-CREDENTIAL" all compare equal.
 */
function normalizeName(name: string): string {
  return name.replace(/[^a-zA-Z0-9]/g, '').toUpperCase();
}
